# Generated by Django 3.1.7 on 2021-03-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
