# Generated by Django 3.1.7 on 2021-03-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0004_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refined_Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('Count', models.PositiveIntegerField(default=0)),
                ('Number_of_sightings', models.PositiveIntegerField(default=0)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildSightApp.location')),
                ('Species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildSightApp.species')),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
