# Generated by Django 3.1.7 on 2021-04-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildSightApp', '0005_auto_20210329_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Sighting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildSightApp.species')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
