# Generated by Django 3.1.7 on 2021-04-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0006_raw_sighting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_sighting',
            old_name='date',
            new_name='date_time',
        ),
    ]
