# Generated by Django 3.1.7 on 2021-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0007_auto_20210403_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_sighting',
            name='credible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw_sighting',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raw_sighting',
            name='image',
            field=models.ImageField(blank=True, max_length=256, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='raw_sighting',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
