# Generated by Django 3.1.7 on 2021-04-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0008_auto_20210406_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_sighting',
            name='image',
        ),
    ]
