# Generated by Django 3.1.7 on 2021-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0009_remove_raw_sighting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_sighting',
            name='credible',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='raw_sighting',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='raw_sighting',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
