# Generated by Django 3.1.7 on 2021-04-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0010_auto_20210406_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_sighting',
            name='image',
            field=models.ImageField(blank=True, max_length=256, upload_to='uploads/'),
        ),
    ]
