# Generated by Django 3.1.7 on 2021-04-08 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wildSightApp', '0012_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_sighting',
            old_name='userId',
            new_name='user',
        ),
        migrations.AddField(
            model_name='raw_sighting',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='Voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='vote',
        ),
    ]
