# Generated by Django 3.1.7 on 2021-04-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0014_auto_20210409_0811'),
        ('wildSightApp', '0014_userprofile'),
    ]

    operations = [
    ]
