# Generated by Django 3.1.7 on 2021-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0016_auto_20210410_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_sighting',
            name='new_species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
