# Generated by Django 3.1.7 on 2021-04-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildSightApp', '0019_auto_20210424_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert_Ratification_Sightings',
            fields=[
                ('raw_sighting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wildSightApp.raw_sighting')),
                ('expert_credible', models.BooleanField(blank=True, default=False)),
            ],
            bases=('wildSightApp.raw_sighting',),
        ),
    ]
